name: Comment on the workflow issues

on:
  issues: 
    types: [oepned]

jobs:
  commentissues:
    runs-on: ubuntu:latest
    steps:
      - name: "dump githhub context"
        run: echo ' {{toJson(github.event) }}' | jq
        shell: bash
  
