name: Comment on the workflow issues

on:
  issues: 
    types: [oepned]
  workflow_dispatch:

jobs:
  commentissues:
    runs-on: ubuntu:latest
    steps:
      - name: "dump githhub context"
        run: echo '${{toJSON(github.event) }}' | jq
        shell: bash
  
